# Generated by Django 5.1.6 on 2025-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('sub1', models.IntegerField()),
                ('sub5', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Studentdata',
        ),
    ]
